import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../models/menu_item.dart';

class MainController extends GetxController {
  final PageController cardController = PageController();

  RxInt courseSelection = 0.obs, navSelection = 0.obs;
  RxList<MenuItem> items = <MenuItem>[
        MenuItem(
            isDrink: true,
            imagePath: 'americano.png',
            stars: 4,
            name: 'Americano',
            time: '4-5',
            reviews: '40+',
            price: 0.9,
            cook: '',
            isSpecials: false,
            isPopular: true,
            isNewest: false,
            isMilkBased: false,
            isCocktail: false,
            hasAlcohol: false),
        MenuItem(
            isDrink: true,
            imagePath: 'americano_cocktail.png',
            stars: 5,
            name: 'Americano Cocktail',
            time: '7-8',
            reviews: '20+',
            price: 1.4,
            cook: 'Rabin Dhoju',
            isSpecials: true,
            isPopular: false,
            isNewest: true,
            isMilkBased: false,
            isCocktail: false,
            hasAlcohol: true),
        MenuItem(
            isDrink: true,
            imagePath: 'cappuccino.png',
            stars: 4,
            name: 'Cappuccino',
            time: '3-5',
            reviews: '50+',
            price: 1.2,
            cook: '',
            isSpecials: false,
            isPopular: true,
            isNewest: false,
            isMilkBased: true,
            isCocktail: false,
            hasAlcohol: false),
        (MenuItem(
            isDrink: true,
            imagePath: 'caramel_coffee.png',
            stars: 5,
            name: 'Caramel Coffee',
            time: '7-8',
            reviews: '40+',
            price: 1.5,
            cook: 'Retesh Thapa Magar',
            isSpecials: true,
            isPopular: true,
            isNewest: false,
            isMilkBased: true,
            isCocktail: false,
            hasAlcohol: false)),
        (MenuItem(
            isDrink: true,
            imagePath: 'chocolate_iced_frappe.png',
            stars: 5,
            name: 'Chocolate Iced Frappe',
            time: '8-10',
            reviews: '45+',
            price: 2.2,
            cook: 'Retesh Thapa Magar',
            isSpecials: true,
            isPopular: true,
            isNewest: true,
            isMilkBased: true,
            isCocktail: true,
            hasAlcohol: false)),
        (MenuItem(
            isDrink: true,
            imagePath: 'cortado.png',
            stars: 3,
            name: 'Cortado',
            time: '3-5',
            reviews: '50+',
            price: 1.2,
            cook: '',
            isSpecials: false,
            isPopular: false,
            isNewest: true,
            isMilkBased: false,
            isCocktail: false,
            hasAlcohol: false)),
        (MenuItem(
            isDrink: true,
            imagePath: 'espresso.png',
            stars: 4,
            name: 'Espresso',
            time: '2-3',
            reviews: '60+',
            price: 0.7,
            cook: '',
            isSpecials: false,
            isPopular: true,
            isNewest: false,
            isMilkBased: true,
            isCocktail: false,
            hasAlcohol: false)),
        (MenuItem(
            isDrink: true,
            imagePath: 'flat_white.png',
            stars: 5,
            name: 'Flat White',
            time: '5-6',
            reviews: '40+',
            price: 1.2,
            cook: '',
            isSpecials: false,
            isPopular: false,
            isNewest: false,
            isMilkBased: true,
            isCocktail: false,
            hasAlcohol: false)),
        (MenuItem(
            isDrink: true,
            imagePath: 'frappe.png',
            stars: 5,
            name: 'Frappe',
            time: '7-8',
            reviews: '50+',
            price: 1.6,
            cook: '',
            isSpecials: true,
            isPopular: true,
            isNewest: false,
            isMilkBased: true,
            isCocktail: false,
            hasAlcohol: false)),
        (MenuItem(
            isDrink: true,
            imagePath: 'cappuccino.png',
            stars: 5,
            name: 'Cappuccino',
            time: '3-5',
            reviews: '50+',
            price: 1.0,
            cook: '',
            isSpecials: false,
            isPopular: false,
            isNewest: false,
            isMilkBased: true,
            isCocktail: false,
            hasAlcohol: false)),
        (MenuItem(
            isDrink: true,
            imagePath: 'glace_coffee.png',
            stars: 5,
            name: 'Glace Coffee',
            time: '3-5',
            reviews: '50+',
            price: 1.0,
            cook: 'Retesh Thapa Magar',
            isSpecials: true,
            isPopular: false,
            isNewest: true,
            isMilkBased: true,
            isCocktail: false,
            hasAlcohol: false)),
        (MenuItem(
            isDrink: false,
            imagePath: 'ice_cream_bowl.png',
            stars: 2,
            name: 'Ice Cream Bowl',
            time: '3-5',
            reviews: '24+',
            price: 1.3,
            cook: '',
            isSpecials: false,
            isPopular: true,
            isNewest: false,
            isMilkBased: true,
            isCocktail: false,
            hasAlcohol: false)),
        (MenuItem(
            isDrink: true,
            imagePath: 'irish_coffee.png',
            stars: 3,
            name: 'Irish Coffee',
            time: '3-5',
            reviews: '24+',
            price: 1.8,
            cook: '',
            isSpecials: false,
            isPopular: true,
            isNewest: false,
            isMilkBased: false,
            isCocktail: true,
            hasAlcohol: true)),
        (MenuItem(
            isDrink: true,
            imagePath: 'mocaccino.png',
            stars: 5,
            name: 'Mocaccino',
            time: '3-5',
            reviews: '38+',
            price: 2.0,
            cook: 'Rabin Dhoju',
            isSpecials: true,
            isPopular: true,
            isNewest: false,
            isMilkBased: true,
            isCocktail: true,
            hasAlcohol: false)),
        (MenuItem(
            isDrink: true,
            imagePath: 'mocha_milkshake_frappe.png',
            stars: 4,
            name: 'Mocha Milkshake Frappe',
            time: '8-10',
            reviews: '34+',
            price: 2.2,
            cook: 'Retesh Thapa Magar',
            isSpecials: false,
            isPopular: true,
            isNewest: true,
            isMilkBased: true,
            isCocktail: true,
            hasAlcohol: false))
      ].obs,
      filteredItems = <MenuItem>[].obs;
}
